# Generated by Django 6.0.1 on 2026-01-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='image',
            field=models.ImageField(blank=True, help_text='Industry card image', null=True, upload_to='industries/'),
        ),
        migrations.AddField(
            model_name='industry',
            name='stat_badge',
            field=models.CharField(default='Fast Delivery', help_text="e.g., 'ISO Certified', 'Fast Delivery'", max_length=50),
        ),
        migrations.AddField(
            model_name='industry',
            name='stat_badge_icon',
            field=models.CharField(default='⚡', help_text='Emoji for badge, e.g., ⚡, ✓', max_length=20),
        ),
        migrations.AddField(
            model_name='industry',
            name='stat_products',
            field=models.CharField(default='100+ Products', help_text="e.g., '200+ Products'", max_length=50),
        ),
        migrations.AlterField(
            model_name='industry',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or icon class', max_length=100),
        ),
    ]
